name: ai_model_server
channels:
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.12
  - pytorch=2.4.0
  - torchvision=0.19.0
  - pytorch-cuda=12.4
  - pyyaml
  - pip
  - pip:
    - ./dist/ai_processing-0.0.0-cp312-cp312-win_amd64.whl  # [win]
    - decord
    - fastapi==0.112.2
    - pycryptodomex==3.20.0
    - pydantic==2.8.2
    - pydantic_core==2.20.1
    - uvicorn
    - requests
    - aiohttp
    - colorlog
    - psutil
    - wmi
    - windows-curses